default:
  image: composer:2

stages:
  - build
  - check
  - test

variables:
  COMPOSER_CACHE_DIR: "$CI_PROJECT_DIR/.composer-cache"

.default_rules:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"

renovate:
  needs: [  ]
  stage: build
  image: renovate/renovate
  variables:
    RENOVATE_CONFIG_FILE: ${CI_PROJECT_DIR}/config/renovate/config.js
    RENOVATE_GIT_AUTHOR: Renovate <renovate@grdev.co.nz>
    RENOVATE_CONSTRAINTS: '{"php":"< 8.2.0"}'
    # LOG_LEVEL: debug
  script:
    - renovate $RENOVATE_EXTRA_FLAGS
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: manual

renovate config validator:
  extends: renovate
  script:
    - renovate-config-validator $RENOVATE_EXTRA_FLAGS
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

composer validate:
  rules:
    - !reference [.default_rules, rules]
  stage: build
  allow_failure: true
  script:
    - composer validate --verbose

composer install:
  rules:
    - !reference [.default_rules, rules]
  needs:
    - composer validate
  stage: build
  script:
    - composer install --no-interaction --ignore-platform-req=ext-gd
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .composer-cache
  artifacts:
    paths:
      - vendor/
      - web/
    expire_in: 1 day

composer changes:
  needs: [  ]
  stage: check
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - composer.lock
  allow_failure: true
  script:
    - PATH=$PATH:$( composer global config home )/vendor/bin
    - git fetch origin
    - composer global require davidrjonas/composer-lock-diff:^1.0
    - composer-lock-diff --from origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME --md | tee composer-changes.txt

composer audit:
  rules:
    - !reference [.default_rules, rules]
  needs:
    - composer install
  stage: check
  allow_failure: true
  script:
    - composer audit | tee composer-audit.txt
  artifacts:
    paths:
      - composer-audit.txt
    when: always

composer outdated:
  rules:
    - !reference [.default_rules, rules]
  needs:
    - composer install
  stage: check
  allow_failure: true
  script:
    - composer outdated | tee composer-outdated.txt
  artifacts:
    paths:
      - composer-outdated.txt
    when: always
