name: Renovate

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 * * * *'  # Run weekly on Sunday at midnight
  workflow_dispatch:  # Allow manual triggering

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2

      - name: self-hosted renovate
        uses: renovatebot/github-action@v42.0.0
        with:
          configurationFile: config/renovate/config.js

  validate:
    name: renovate config validate
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@v1.0.1
